In [ ]:
import pandas as pd
import numpy as np


x = np.array([[1, 2, 3] ,
             [4, 5, 6] ,
             [7, 8, 9]])

x.shape



array([2, 5, 8])

In [6]:
x[: , 1]

array([2, 5, 8])

In [7]:
x[0:1 , :]

array([[1, 2, 3]])

In [8]:
x[-1, -1]

np.int64(9)

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x[-1, :]

array([7, 8, 9])

In [11]:
x[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])